# Configuration file for Luminos.     http://luminos.menteslibres.org
#
# You are viewing a YAML formatted file, read more about the format
# at http://www.yaml.org.
#
# Note: Use two space indentations instead of the \t character.
#
#

page:
  # Name of the site.
  brand: "Gestii Knowledge Base"

  # Some properties for <head>.
  head:
    # Title that appears on the <title> tag.
    title: "Gestii Knowledge Base"

  # Some properties for <body>.
  body:
    # Title that appears on the <h1> tag.
    title: "A new Luminos project"

    # Top navigation bar.
    menu:
      - { text: "Visitas", url: "/visitas" }
      - { text: "Cuestionarios", url: "/cuestionarios" }
      - { text: "Administradores", url: "/administradores" }
      - { text: "Mapas", url: "/mapas" }
      - { text: "Grupos", url: "/grupos" }
      - { text: "Misc", url: "/misc" }

    # Top-right navigation helper.
    menu_pull:
      - { text: "Gestii", url: "http://gestii.com" }
